spring:
  application:
    name: ProjectManagementSystem
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Root123$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
